### PR TITLE
Add and integrate match service

### PR DESCRIPTION
**Pull request by samuelim01**
## Description

Create and integrated match service with frontend.

* Match service with API calls, and consumers and producers using RabbitMQ (for now).
*  Documentation and logging for match service
* Integrate match service with matching page for initial match request, cancellation, and polling of match request status
* Frontend timer on match page
* Docker dependencies to ensure services do not fail to start up, especially match service due to a dependency on RabbitMQ.

## Checklist

- [x] I have updated documentation
- [x] All tests passing

## Screenshots (if applicable)
image
image
image

### CODE REVIEW

**Comment by limcaaarl** [comment]
Bug: A user can have multiple instances of match found.

Steps: 
1. Open 2 tabs for user1, and another 2 tabs for user2.
2. Select and match the preferences as per usual, such that the first tab for both user1 and user2 have common topics and same difficulty and the same for the second tab for both user1 and user2.
3. Start matching
4. Match found will be triggered for both tabs for both users, resulting in 2 instances of match found for both users.

**Comment by samuelim01** [comment]
> Bug: A user can have multiple instances of match found.
> 
> Steps:
> 
> 1. Open 2 tabs for user1, and another 2 tabs for user2.
> 2. Select and match the preferences as per usual, such that the first tab for both user1 and user2 have common topics and same difficulty and the same for the second tab for both user1 and user2.
> 3. Start matching
> 4. Match found will be triggered for both tabs for both users, resulting in 2 instances of match found for both users.

This was intended behaviour, such that a user can be in multiple sessions at the same time. However, a user will not pair up with themselves.

**Review by limcaaarl — APPROVED** [review]
LGTM!

**Review by McNaBry — APPROVED** [review]
LGTM

**Pull request merged**
